name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands

      - name: Hassfest Validation
        uses: home-assistant/actions/hassfest@master

  validate-hacs:
    runs-on: ubuntu-latest
    name: Validate HACS
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    runs-on: ubuntu-latest
    name: Validate with hassfest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
